### ISSUE TITLE
Github Actions is failing

### ISSUE THREAD

**Issue by Tejas2805** [eskatos/gradle-command-action#11] opened 2020-03-06 10:34 UTC
![Screen Shot 2020-03-06 at 6 29 37 PM](https://user-images.githubusercontent.com/35946746/76075833-a855ee80-5fd8-11ea-91e3-f60c03edaad5.png)

Wanted know why is the build failing? 

![Screen Shot 2020-03-06 at 6 34 17 PM](https://user-images.githubusercontent.com/35946746/76076090-1f8b8280-5fd9-11ea-98ad-241f9b986130.png)

^This is my code for Github Actions

**Comment by eskatos** [comment] 2020-05-10 10:29
The action seems to be executing Gradle properly.
The `NullPointerException` points to your build script.
Hard to tell with so few informations but I bet the problem is that your build script is expecting something to be set but it isn't.
Closing as it doesn't seem to be about the action, feel free to reopen if you can provide information pointing at a problem with the action.

**Closed by eskatos** 2020-05-10 10:29 UTC
